# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PHk22z3Kvg8USvxq0VYMltzaIeClnKht
"""

#Assignment 1
#create a two different examples for collective datatypes in python
#EXAMPLE 1
# Creating a list of integers
numbers = [1, 2, 3, 4, 5]
numbers.append(6)
print(numbers[0])
numbers[1] = 10
for number in numbers:
    print(number)

#EXAMPLE 2
# Creating a set of fruits
fruits = {"apple", "banana", "orange"}
fruits.add("kiwi")
fruits.remove("banana")
print("apple" in fruits)
for fruit in fruits:
    print(fruit)

fruits = {"apple", "banana", "orange"}
fruits.add("kiwi")
fruits.discard("banana")
print("apple" in fruits)
for fruit in fruits:
    print(fruit)